### ISSUE TITLE
Python bindings broken on Fedora >= 39

### ISSUE THREAD

**Issue by tuxmaster5000** [bareos/bareos#1803]
### Bareos component version

23.0.2

### Steps to reproduce

Try to use the python bindings

### Expected results

Working python bindings

### Actual results

It will fails, because the needed python-sslpsk don't run under Python >= 3.12 and it looks like the project is dead.

### Environment

```markdown
- Python: >= 3.12
```

### Relevant log output

```shell
Error in python-sslpsk:
======================================================================
ERROR: testClient (test_sslpsk.SSLPSKTest.testClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/sslpsk-1.0.0/sslpsk/test/test_sslpsk.py", line 80, in testClient
    self.client_psk_sock = sslpsk.wrap_socket(self.client_socket, psk=self.psk, ciphers='PSK-AES256-CBC-SHA',
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/sslpsk-1.0.0/sslpsk/sslpsk.py", line 99, in wrap_socket
    sock = ssl.wrap_socket(*args, **kwargs)
           ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

----------------------------------------------------------------------
Ran 1 test in 0.012s

FAILED (errors=1)
    sock = ssl.wrap_socket(*args, **kwargs)
           ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
testClient (sslpsk.test.test_sslpsk.SSLPSKTest.testClient) ... Exception in thread Thread-2 (accept):
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
ERROR

======================================================================
ERROR: testClient (sslpsk.test.test_sslpsk.SSLPSKTest.testClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/sslpsk-1.0.0/sslpsk/test/test_sslpsk.py", line 80, in testClient
    self.client_psk_sock = sslpsk.wrap_socket(self.client_socket, psk=self.psk, ciphers='PSK-AES256-CBC-SHA',
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/sslpsk-1.0.0/sslpsk/sslpsk.py", line 99, in wrap_socket
    sock = ssl.wrap_socket(*args, **kwargs)
           ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

----------------------------------------------------------------------

https://docs.python.org/3.12/whatsnew/3.12.html#removed
Since 3.7 deprecated. 
So it looks like, we need another solution then using python-sslpsk.
```

**Comment by joergsteffens** [comment]
We're aware of the problems with python-sslpsk. Good news are, that Python 3.13 added native support for TLS-PSK. Bareos is already adapted to use it., see PR #1756 (and the bareos-23 backport PR #1764).
This also means, that we do not plan to spend more effort to  python-sslpsk. However, you might want to check if https://github.com/drbild/sslpsk/pull/28 solves this problem.

**Comment by tuxmaster5000** [comment]
Ah, that's good news that it works without Python 3.13. But it will probably be a while before the big manufacturers like Oracle, SuSE or RedHat deliver Python 3.13.  But since it is only needed for accessing the Director and not for the add-on structure, you can simply install Python 3.13 in addition. This would work for Fedora. Or am I seeing something wrong?

**Comment by joergsteffens** [comment]
You describing it correctly. Yes, this problem is only related to the python-bareos library, which can be used to write Python script which interact with the Director.
It does not affect the Bareos Python plugins.
Therefore I will close this issue. Feel free to reopen it, when there is new content.
