### ISSUE TITLE
Bareos 23 webui returns error after login

### ISSUE THREAD

**Issue by bonettia** [bareos/bareos#2038]
### Bareos component version

director version: 23.1.1~pre3.47aeb30a1
webui version: 23.1.1~pre3.47aeb30a1-149

### Steps to reproduce

go to bareos webui page, log in

### Expected results

i should be able to login into the webui

### Actual results

i get error
Error: API 2 not available on director. Please upgrade to version 15.2.2 or greater and/or compile with jansson support.
if i refresh the page i get error 500

### Environment

```markdown
- OS: `Ubuntu 22.04`
- component:
```

### Relevant log output

```shell
log from apache2 error.log
[Mon Nov 25 16:34:02.397283 2024] [proxy_fcgi:error] [pid 1312865:tid 140115674338880] [client 10.0.166.120:44666] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /usr/share/bareos-webui/module/Application/src/Application/Controller/Plugin/CommandACLPlugin.php:53\nStack trace:\
n#0 /usr/share/bareos-webui/module/Application/src/Application/Controller/Plugin/CommandACLPlugin.php(53): array_key_exists()\
n#1 /usr/share/bareos-webui/module/Dashboard/src/Dashboard/Controller/DashboardController.php(56): Application\\Controller\\Plugin\\CommandACLPlugin->getInvalidCommands()\
n#2 /usr/share/bareos-webui/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Dashboard\\Controller\\DashboardController->indexAction()\
n#3 [internal function]: Zend\\Mvc\\Controller\\AbstractActionController->onDispatch()\
n#4 /usr/share/bareos-webui/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func()\
n#5 /usr/share/bareos-webui/vendor/zendframework/zend-eventmanager/src/EventManager.php(211): Zend\\EventManager\\EventManage...'
```

### Anything else?

this is a freshly installed bareos 23 environment i wanted to test some features with, i followed the guide on bareos documentation for installation

**Comment by arogge** [comment]
What is the CommandACL this user has configured (either directly, via Profile or both)?
