### ISSUE TITLE
 Unable to backup MariaDB 11.4 Incremental (bareos 23)

### ISSUE THREAD

**Issue by tuxmaster5000** [bareos/bareos#2091]
### Bareos component version

bareos-fd --version:
23.1.1

### Steps to reproduce

Using the MariaDB Python Add-On

### Expected results

Working backup 

### Actual results

error:
```
28-Dez 19:08 terrortux-fd JobId 23418: Fatal error: bareosfd: Traceback (most recent call last):
  File "/usr/lib64/bareos/plugins/BareosFdWrapper.py", line 63, in start_backup_file
    return bareos_fd_plugin_object.start_backup_file(savepkt)
  File "/usr/lib64/bareos/plugins/bareos-fd-mariabackup.py", line 308, in start_backup_file
    with open("%s/xtrabackup_checkpoints" % self.tempdir) as lsnfile:
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/tmp/tmpx9gqy58i/xtrabackup_checkpoints'

28-Dez 19:08 terrortux-fd JobId 23418: Fatal error: filed/fd_plugins.cc:743 Command plugin "python:module_path=/usr/lib64/bareos/plugins:module_name=bareos-fd-mariabackup:mycnf=/etc/bareos/my.cnf:restorecommand=/bin/true": startBackupFile failed.
```

### Environment

```markdown
- OS: Rocky 9.5
- component: MariaDB 11.4 LTS
```

### Anything else?

It looks like the needed files was renamed with MariaDB LTS 11.4 from 
```
xtrabackup_checkpoints  -> mariadb_backup_checkpoints
xtrabackup_backup_info -> mariadb_backup_info

```
After sed "%s/xtrabackup_checkpoints/mariadb_backup_checkpoints/g" on /usr/lib64/bareos/plugins/bareos-fd-mariabackup.py the Full backup works, but the first incremental fails with:
`Fatal error: python3-fd-mod: Could not get LSN with command "echo 'SHOW ENGINE INNODB STATUS' | mysql --defaults-extra-file=/etc/bareos/my.cnf  -r | grep 'Log sequence number' | awk '{ print $4 }'", Error: b'/bin/sh: Zeile 1: mysql: Kommando nicht gefunden.\n'`
Since 11.4 the command mysql was renamed to mariadb.

**Comment by tuxmaster5000** [comment]
Replacing mysql with mariabd in line 125 of the file ‘bareos-fd-mariabackup.py’ also solves the 2nd problem.

**Comment by tuxmaster5000** [comment]
In the master it looks like fixed, so an backport to bareos 23 will be needed.

**Comment by bruno-at-bareos** [comment]
A backport to 24 has been created already https://github.com/bareos/bareos/pull/2077 
which is already available in https://download.bareos.org/current

I guess if you want to adapt for bareos-23 you either can make a PR backport request or backport the changes for yourself.

**Comment by tuxmaster5000** [comment]
https://github.com/bareos/bareos/pull/2077 will not fix the python module itself, because it don't contains changed for it.

**Comment by tuxmaster5000** [comment]
Very strange :(
In the tar ball(https://github.com/bareos/bareos/archive/refs/tags/Release/23.1.1.tar.gz), the command will be mysql, but in the git(bareos-23 branch) the command will be mariadb. But Git says, that the file was changes last year and the tar ball is 28 days old. The whole thing looks a bit inconsistent.

**Comment by tuxmaster5000** [comment]
The same with the file name problem of the checkpoint file.  Broken in tar ball, correct in the one year old  git file.

**Comment by bruno-at-bareos** [comment]
Yeah about backporting you also need PR #1835

Otherwise sorry I wasn't able to understand the last two comment.

**Comment by bruno-at-bareos** [comment]
I'm not sure about the fact you described, as git branch bareos-23 doesn't contain the code present in bareos-24 (or master).
See master https://github.com/bareos/bareos/blob/a2e4f6ebf86d65b3bb0d7318f5587aa28530a015/core/src/plugins/filed/python/mariabackup/bareos-fd-mariabackup.py

compared to bareos-23 branch

https://github.com/bareos/bareos/blob/4922b502b/core/src/plugins/filed/python/mariabackup/bareos-fd-mariabackup.py

```
fe569b74f6038668e35d9f52e5ceaeb3e4c1a769969a04f2622d26f817c8297e  core/src/plugins/filed/python/mariabackup/bareos-fd-mariabackup.py
```

which is exactly the one present in bareos 23.1.1 tgz 
```
curl -L -O https://github.com/bareos/bareos/archive/refs/tags/Release/23.1.1.tar.gz
tar -xf 23.1.1.tar.gz
cd bareos-Release-23.1.1/
sha256sum core/src/plugins/filed/python/mariabackup/bareos-fd-mariabackup.py fe569b74f6038668e35d9f52e5ceaeb3e4c1a769969a04f2622d26f817c8297e  core/src/plugins/filed/python/mariabackup/bareos-fd-mariabackup.py
```

Please check your download and working area.

**Comment by bruno-at-bareos** [comment]
Reopening as we got a contribution to create the backport in #2093

**Comment by bruno-at-bareos** [comment]
Closing issue as the #2093 PR didn't succeed
